# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: thingvisor.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'thingvisor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10thingvisor.proto\"(\n\x15InitializationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x16InitializationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2e\n\x12ThingVisorNotifier\x12O\n\x1cNotifyInitializationComplete\x12\x16.InitializationRequest\x1a\x17.InitializationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thingvisor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIALIZATIONREQUEST']._serialized_start=20
  _globals['_INITIALIZATIONREQUEST']._serialized_end=60
  _globals['_INITIALIZATIONRESPONSE']._serialized_start=62
  _globals['_INITIALIZATIONRESPONSE']._serialized_end=102
  _globals['_THINGVISORNOTIFIER']._serialized_start=104
  _globals['_THINGVISORNOTIFIER']._serialized_end=205
# @@protoc_insertion_point(module_scope)
