apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: f4i-tv-weather
spec:
  selector:
    matchLabels:
      app: f4i-tv-weather
  replicas: 1
  template:
    metadata:
      labels:
        app: f4i-tv-weather
    spec:
      containers:
      - name: wheater
        image: tryuu/viriot_thingvisor_weather:latest
        ports:
        - containerPort: 8089 
